import os
from pathlib import Path

import click
import yaml


WORKSPACE_TEMPLATE = """\
workspace "{name}" "Architecture model for {name}" {{

    !identifiers hierarchical

    model {{
        # Define people (actors) who use the system
        # user = person "User" "Description"

        # Define the software system
        # mySystem = softwareSystem "System Name" "Description" {{
        #     container1 = container "Container" "Description" "Technology" {{
        #         component1 = component "Component" "Description" "Technology" {{
        #             properties {{
        #                 code_path "src/**/*.py"
        #             }}
        #         }}
        #     }}
        # }}

        # Define relationships
        # user -> mySystem "Uses"
        # mySystem.container1 -> mySystem.container2 "Calls" "HTTPS"
    }}

    views {{
        # Views are generated by the init agent

        styles {{
            element "Software System" {{
                background "#1168bd"
                color "#ffffff"
            }}
            element "Container" {{
                background "#438dd5"
                color "#ffffff"
            }}
            element "Component" {{
                background "#85bbf0"
                color "#000000"
            }}
            element "Person" {{
                shape Person
                background "#08427b"
                color "#ffffff"
            }}
            element "Database" {{
                shape Cylinder
            }}
            element "External" {{
                background "#999999"
            }}
        }}
    }}
}}
"""

PRACTICES_TEMPLATE = """\
# Architectural Practices

## Principles
- KISS — prefer the simplest solution that meets the requirement
- Single Responsibility — each component has one clear purpose
- Loose Coupling — minimize dependencies between components
- High Cohesion — related functionality belongs together

## Conventions
- New components must have code_path mappings
- External integrations are modeled as external software systems
- Database-per-service when services need independent data ownership
- Async communication between containers when possible
"""


@click.command("init")
@click.option("--name", required=True, help="Project name for the workspace.")
@click.option(
    "--root",
    default=None,
    type=click.Path(exists=True, file_okay=False),
    help="Project root directory. Defaults to current directory.",
)
def init_cmd(name, root):
    """Initialize a .pathfinder/ directory with workspace template and config."""
    project_root = Path(root) if root else Path.cwd()
    pf_dir = project_root / ".pathfinder"

    if pf_dir.exists():
        click.echo(f"Error: {pf_dir} already exists. Remove it first or use a different directory.", err=True)
        raise SystemExit(1)

    pf_dir.mkdir(parents=True)

    # Write config.yaml
    config = {"project_name": name, "version": "0.2.0"}
    (pf_dir / "config.yaml").write_text(yaml.dump(config, default_flow_style=False))

    # Write workspace.dsl template
    (pf_dir / "workspace.dsl").write_text(WORKSPACE_TEMPLATE.format(name=name))

    # Write practices.md
    (pf_dir / "practices.md").write_text(PRACTICES_TEMPLATE)

    click.echo(f"Initialized .pathfinder/ in {project_root}")
    click.echo(f"  workspace.dsl  — architecture template")
    click.echo(f"  config.yaml    — project config")
    click.echo(f"  practices.md   — architectural best practices (edit to customize)")
    click.echo()
    click.echo("Next steps:")
    click.echo("  pathfinder install   # Copy skills + agents to .claude/")
    click.echo("  pathfinder start     # Start Structurizr Server + MCP")
